name: Code Checks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.1.4
      with:
          python-version: 3.12.0
          architecture: x64

    - run: pip install --upgrade pip
    - run: pip install black mypy ruff
    - run: pip install -r requirements.txt # to install all library stubs
    - run: black --diff --check $(git ls-files '*.py')
    - run: mypy $(git ls-files '*.py')
    - run: ruff $(git ls-files '*.py')